events {
    worker_connections 1024;
}

http {
    upstream jarvis {
        server jarvis:3030;
    }

    upstream whispera {
        server whispera:8011;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://jarvis;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /whispera/ {
            proxy_pass http://whispera/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}